Repository suyoungSwim/next-netflix-21th, pull requests merged in 2025-05, with the labels that each got.

#3 ✨ feat: 넷플릭스 랜딩페이지 구현
  next-netflix-21th/package.json
  next-netflix-21th/public/icons/header/logo.svg
  next-netflix-21th/public/lotties/LandingLottie.json
  next-netflix-21th/public/sounds/NetflixIntroSound.mp3
  next-netflix-21th/src/app/page.tsx
  next-netflix-21th/src/types/svg.d.ts
  next-netflix-21th/yarn.lock
Labels: feature UI

#5 🐛 fix: heroslider 스와이퍼 디자인 수정 및 slide 방향 수정
  next-netflix-21th/src/app/page.tsx
  next-netflix-21th/src/components/home/HeroSlider.tsx
Labels: Refactor, Bug, Design

#4 ✨ feat: 장르별 영화, 넷플릭스 오리지널, 프리뷰, 한국 영화 가져오기
  next-netflix-21th/package.json
  next-netflix-21th/src/apis/axios.ts
  next-netflix-21th/src/apis/tmdb.ts
  next-netflix-21th/src/app/globals.css
  next-netflix-21th/src/app/home/page.tsx
  next-netflix-21th/src/app/movie/[id]/page.tsx
  next-netflix-21th/src/app/not-found.tsx
  next-netflix-21th/src/components/home/GenrePreview.tsx
  next-netflix-21th/src/components/home/HeroSlider.tsx
  next-netflix-21th/src/components/home/KoreaMovie.tsx
  next-netflix-21th/src/components/home/NetflixOriginal.tsx
  next-netflix-21th/src/components/home/Preview.tsx
  next-netflix-21th/src/components/home/SectionTitle.tsx
  next-netflix-21th/src/components/layout/BottomNavBar.tsx
  next-netflix-21th/src/components/layout/Header.tsx
  next-netflix-21th/src/types/tmdb.ts
  next-netflix-21th/yarn.lock
Labels: feature UI, API, Design, chore

#6 🔧 Chore: build.sh 파일 추가
  next-netflix-21th/build.sh
Labels: chore

#7 ♻️ Refactor: Swiper 컴포넌트로 분리
  next-netflix-21th/public/icons/file.svg
  next-netflix-21th/public/icons/globe.svg
  next-netflix-21th/public/icons/next.svg
  next-netflix-21th/public/icons/vercel.svg
  next-netflix-21th/public/icons/window.svg
  next-netflix-21th/src/components/home/GenrePreview.tsx
  next-netflix-21th/src/components/home/KoreaMovie.tsx
  next-netflix-21th/src/components/home/MovieSwiper.tsx
  next-netflix-21th/src/components/home/NetflixOriginal.tsx
  next-netflix-21th/src/components/home/Preview.tsx
Labels: Refactor

#10 ✨ feat: 검색 페이지 UI 및 기능 구현
  next-netflix-21th/.prettierrc
  next-netflix-21th/package.json
  next-netflix-21th/public/icons/search/CloseIcon.svg
  next-netflix-21th/public/icons/search/PlayIcon.svg
  next-netflix-21th/public/icons/search/SearchInputIcon.svg
  next-netflix-21th/src/apis/tmdb.ts
  next-netflix-21th/src/app/globals.css
  next-netflix-21th/src/app/home/page.tsx
  next-netflix-21th/src/app/layout.tsx
  next-netflix-21th/src/app/not-found.tsx
  next-netflix-21th/src/app/page.tsx
  next-netflix-21th/src/app/search/page.tsx
  next-netflix-21th/src/components/home/BannerOption.tsx
  next-netflix-21th/src/components/home/HeroSlider.tsx
  next-netflix-21th/src/components/home/MovieSwiper.tsx
  next-netflix-21th/src/components/home/SectionTitle.tsx
  next-netflix-21th/src/components/layout/BottomNavBar.tsx
  next-netflix-21th/src/components/layout/Header.tsx
  next-netflix-21th/src/components/search/SearchBar.tsx
  next-netflix-21th/src/components/search/SearchCardItem.tsx
  next-netflix-21th/src/components/skeleton/BannerSkeleton.tsx
  next-netflix-21th/src/components/skeleton/SearchSkeletonCard.tsx
  next-netflix-21th/src/components/skeleton/SkeletonCard.tsx
  next-netflix-21th/src/hooks/useDebounce.ts
  next-netflix-21th/src/hooks/useInfiniteScroll.ts
  next-netflix-21th/src/hooks/useSearch.ts
  next-netflix-21th/src/utils/throttle.ts
  next-netflix-21th/tsconfig.json
  next-netflix-21th/yarn.lock
Labels: feature UI, API, Refactor, Design

#12 ✨ feat: detail 페이지 제작 및 링크 추가
  next-netflix-21th/src/apis/tmdb.ts
  next-netflix-21th/src/app/detail/[media_type]/[id]/page.tsx
  next-netflix-21th/src/app/movie/[id]/page.tsx
  next-netflix-21th/src/components/home/HeroSlider.tsx
  next-netflix-21th/src/components/home/MovieSwiper.tsx
  next-netflix-21th/src/components/search/SearchCardItem.tsx
  next-netflix-21th/src/hooks/useSearch.ts
  next-netflix-21th/src/hooks/useSearchFetcher.ts
  next-netflix-21th/src/types/tmdb.ts
Labels: feature UI, API
